language: python
sudo: required
group: deprecated-2017Q4
python:
  - "2.7"
env:
  global:
    - TZ=Europe/Kiev
cache:
  directories:
    - eggs
before_install:
  - sh bootstrap.sh
install:
  - bin/buildout -N remotes:branch=$TRAVIS_BRANCH
  - bin/develop up --force
script:
  - bin/py.test openprocurement/bridge/templatesregistry/tests/ --cov=openprocurement/bridge/templatesregistry
after_success:
  - bin/coveralls
